server:
  port: 9090
spring:
  application:
    name: rabbitmq
  rabbitmq:
    host: 129.204.12.131
    port: 5672
    username: hazer
    password: hazer
    virtual-host: /mq
    connection-timeout: 15000
    publisher-returns: true
    template:
      mandatory: true

