server:
  port: 8081
spring:
  profiles:
    active: dev
  messages:
    basename: i18n.login
  thymeleaf:
    cache: false

---
server:
  port: 8080
spring:
  profiles: dev
---
server:
  port: 8083
spring:
  profiles: prod