elasticsearch:
  scheme: http
  clusterNodes: 10.226.21.38:9200,10.226.21.39:9200,10.226.21.40:9200
  connectTimeOut: 500000
  socketTimeOut: 400000
  connectionRequestTimeOut: 10000
  maxConnectNum: 100
  maxConnectPerRoute: 100
  numberOfShards: 3
  numberOfReplicas: 3
  username: elastic
  password: kw8LkFpsTmY3

server:
  port: 9090
  servlet:
    context-path: /es


